### ISSUE TITLE
alfred workflow error

### ISSUE THREAD

**Issue by dataofmen** [ChewingPencils/evernote_alfred_workflows#1]
Thank you for your workflow and sharing it.
I got some error message as below:

[ERROR: alfred.workflow.action.applescript] {
    NSAppleScriptErrorAppName = Evernote;
    NSAppleScriptErrorBriefMessage = "Operation would exceed monthly upload allowance.";
    NSAppleScriptErrorMessage = "Evernote got an error: Operation would exceed monthly upload allowance.";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {1396, 77}";
}

Could you check it?

**Comment by ChewingPencils** [comment]
What action is giving you the error?

**Comment by dataofmen** [comment]
Thank you for reply.

I found that evernote has some error for this. Your code may be perfect.
you don't need to care about it.

Thanks,
Hyuck Min
